blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .api_urls import urlpatterns as api_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('modules.Home.urls', namespace='Home',  app_name='Home'), name='Home'),
    url(r'^publicaciones/', include('modules.Publicaciones.urls', namespace='Publicaciones', app_name='Publicaciones'), name='Publicaciones'),
    #urls api
    url(r'^api/v1/', include(api_urls)),
]

modules/Home/urls.py
from django.conf.urls import url
from .views import Index,Contacto,Otros,Signup,Login,Logout

urlpatterns = [
    url(r'^$', Index, name='index'),
    url(r'^contacto$', Contacto, name='contacto'),
    url(r'^otros/(?P<num>[0-9]+)/$', Otros, name='otros'),
    url(r'signup$', Signup, name='signup'),
    url(r'login$', Login, name='login'),
    url(r'logout$', Logout, name='logout')
    #url(r'^$', admin.site.urls),
]

modules/Publicaciones/urls.py
from django.conf.urls import url
from .views import Index, Add

urlpatterns = [
    url(r'^$', Index, name='index'),
    url(r'^add$', Add, name='add')
]

modules/Publicaciones/models.py
from django.db import models
from django.contrib.auth.models import User

TAGS = (
    ('TC','Tecnología'),
    ('CT','Cientifico'),
    ('PR','Programacion'),
)

#Manager de Publicaciones
'''
class LoloPublicacionesManager(models.Manager):

    def get_queryset(self):
        return super(LoloPublicacionesManager,self).get_queryset().filter(autor__username='lolo')
'''
#Clase de modelo principal
class Publicacion(models.Model):
    # Generador de id primaria(
    id = models.AutoField(primary_key = True)
    # Varchar con un recomendado de 50 caracteres
    nombre = models.CharField(max_length = 50)
    # Area de texto descriptivo
    contenido = models.TextField()
    # Timestamps
    fecha = models.DateField(auto_now_add=True)
    # Relación 1 a muchos inversa
    autor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='publicaciones')
    # Enum
    tags = models.CharField(choices=TAGS, max_length=50)
    #Imagen relacionada
    imagen = models.ImageField(upload_to='Publicaciones/', blank=True, null=True)
    # Llamado al Manager
    #lolo_publish = LoloPublicacionesManager()

    def __str__(self):
        return "%s %s" % ("Publicacion: ", self.nombre)

modules/Home/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User

class LoginForm(ModelForm):

    class Meta:
        model = User
        fields = ['username','password']

modules/Home/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from .forms import LoginForm

# Create your views here.

def Index(request):
    user = request.user
    return render(request,'Home/index.html',{'user':user})

def Contacto(request):
    return HttpResponse('Contactame pls')

def Otros(request,num):
    return HttpResponse('Pagina de otros numero ' + num)

def Login(request):
    #Se envian los datos del usuario y se validan
    if request.method == 'POST':
        user = authenticate(username=request.POST['username'],password = request.POST['password'])
        if user is not None:
            login(request,user)
            return redirect('Home:index')
        else:
            return HttpResponse('Error en usuario o contraseña')
    else:
        return render(request,'Home/login.html')

def Logout(request):
    logout(request)
    return redirect('Home:index')


def Signup(request):
    #Se envian los datos al POST del signup
    if request.method == 'POST':
        #Se asignan las variables capturadas del form
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        #Verificacion si el nombre de usuario ya existe
        user = User.objects.get(username=username)
        if user is None:
            #Se crea el usuario
            user = User.objects.create_user(
                first_name = first_name,
                last_name = last_name,
                username = username,
                password = password,
                email = email
            )
            user.save()
            return HttpResponse('Usuario registrado')
        else:
            #Se manda un mensaje de error
            return HttpResponse('El usuario ya existe')

    else:

        return render(request,'Home/signup.html')

modules/Publicaciones/views.py
from django.shortcuts import render,redirect
from .models import TAGS, Publicacion
from .functions import handle_uploaded_file

def Index(request):

    public = [
    {
        "nombre" : "Mi primer Proyecto en Django",
        "auto" : "Kevin Tovar",
        "fecha" : "07-02-2017",
        "rating" : 5
    },
    {
        "nombre" : "Otro Proyecto en Django",
        "auto" : "Masiosare",
        "fecha" : "07-02-2017",
        "rating" : 4
    },
    {
        "nombre" : "Ultimo Proyecto en Django",
        "auto" : "Clemente",
        "fecha" : "07-02-2017",
        "rating" : 3
    },
    ]

    return render(request,'Publicaciones/index.html',{ 'publicaciones':public })

def Add(request):

    if request.method == 'POST':
        if request.user.is_authenticated():
            types = {'image/jpeg':'.jpg','image/png':'.png','image/gif':'.gif'}
            image_name = request.FILES['imagen'].name + types[request.FILES['imagen'].content_type]
            publicacion = Publicacion()
            publicacion.nombre = request.POST['nombre']
            publicacion.contenido = request.POST['contenido']
            publicacion.tags = request.POST['tags']
            publicacion.autor = request.user
            publicacion.imagen = handle_uploaded_file(request.FILES['imagen'], image_name)

            publicacion.save()

            return redirect('Publicaciones:index')
    else:
        dict_tags = dict((x,y) for x,y in TAGS)
        return render(request, 'Publicaciones/add.html',{'tags':dict_tags})

templates/Home/index.html
{%extends 'base.html'%}
{%load static%}
{%block 'title'%}Inicio{%endblock%}
{%block 'main'%}
    <p>
		Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt
		ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
		laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
		voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
		non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	</p>
{%endblock %}

templates/Home/login.html
{%extends 'base.html'%}
{%load static%}
{%block 'title'%}Iniciar sesión{%endblock%}
{%block 'main'%}
<div class="row">
    <form class="col s12" action="{% url 'Home:login' %}" method="POST">
        {%csrf_token%}
        <div class="row">
            <div class="input-field col s12">
                <input name="username" type="text" id="username" class="validate">
                <label for="username">Nombre de usuario</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input name="password" id="password" type="password" class="validate">
                <label for="password">Password</label>
            </div>
        </div>
        <input type="submit" name="" value="Enviar">
    </form>
</div>
{%endblock %}

templates/Home/signup.html
{%extends 'base.html'%}
{%load static%}
{%block 'title'%}Registrarse{%endblock%}
{%block 'main'%}
<div class="row">
    <form class="col s12" action="{% url 'Home:signup' %}" method="POST">
        {%csrf_token%}
        <div class="row">
            <div class="input-field col s6">
                <input name="first_name" id="first_name" type="text" class="validate">
                <label for="first_name">First Name</label>
            </div>
            <div class="input-field col s6">
                <input name="last_name" id="last_name" type="text" class="validate">
                <label for="last_name">Last Name</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input name="username" type="text" id="username" class="validate">
                <label for="username">Nombre de usuario</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input name="password" id="password" type="password" class="validate">
                <label for="password">Password</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input name="email" id="email" type="email" class="validate">
                <label for="email">Email</label>
            </div>
        </div>
        <input type="submit" name="" value="Enviar">
    </form>
</div>
{%endblock %}

templates/Publicaciones/add.html
{%extends 'base.html'%}
{%block 'title'%}Publicaciones | add{%endblock%}
{%block 'main'%}
    <form action="{% url 'Publicaciones:add' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="row">
            <div class="input-field col s12">
                <input type="text" name="nombre">
                <label for="nombre">Nombre</label>
            </div>
            <div class="input-field col s12">
                <textarea name="contenido"></textarea>
                <label for="contenido">Descripcion</label>
            </div>
            <div class="input-field col s12">
                <select name="tags">
                    <option value="" disabled selected>Escoge una etiqueta</option>
                    {% for key,value in tags.items%}
                        <option value="{{key}}">{{value}}</option>
                    {% endfor %}
                </select>
                <label>Seleccionar etiqueta</label>
            </div>
            <input type="file" name="imagen" accept="image/*">
            <input type="submit" class="btn">
        </div>
    </form>
{%endblock %}

templates/Publicaciones/index.html
{%extends 'base.html'%}
{%load static%}
{%block 'title'%}Publicaciones{%endblock%}
{%block 'main'%}
    {%for publicacion in publicaciones%}
        {%for key,item in publicacion.items%}
            {{key}} : {{item}} <br>
        {%endfor%}
        <hr>
    {%endfor%}

    <a href="{% url 'Publicaciones:add' %}">Añadir</a>
{%endblock %}

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block 'title' %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
</head>
<body>
    <nav>
        <div class="nav-wrapper">
            <a href="#" class="brand-logo">BLog backend</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
            {% if user.is_authenticated %}
                <li><b>Hola {{user.username}}</b></li>
                <li><a href="#">Mi perfil</a></li>
                <li><a href="{% url 'Publicaciones:index'%}">Publicaciones</a></li>
                <li><a href="{% url 'Home:logout'%}">Cerrar Sesión</a></li>
            {% else %}
                <li><a href="{% url 'Home:signup'%}">Sign up</a></li>
                <li><a href="{% url 'Home:login' %}">Sign in</a></li>
            {% endif %}
            </ul>
        </div>
    </nav>
    {% block 'main'%}
    {% endblock%}
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/materialize.min.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
</body>
</html>